-- MySQL Script generated by MySQL Workbench
-- Tue Oct 19 21:35:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IACENTERDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IACENTERDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IACENTERDB` DEFAULT CHARACTER SET utf8 ;
USE `IACENTERDB` ;

-- -----------------------------------------------------
-- Table `IACENTERDB`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IACENTERDB`.`File` ;

CREATE TABLE IF NOT EXISTS `IACENTERDB`.`File` (
  `idFile` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `nameFile` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `path` VARCHAR(50) NULL,
  `pathThumbnail` VARCHAR(50) NULL,
  PRIMARY KEY (`idFile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IACENTERDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IACENTERDB`.`User` ;

CREATE TABLE IF NOT EXISTS `IACENTERDB`.`User` (
  `userName` VARCHAR(45) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `lastName` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `privilege` INT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`userName`),
  CONSTRAINT `fk_User_File`
    FOREIGN KEY (`userName`)
    REFERENCES `IACENTERDB`.`File` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
